### ISSUE TITLE
This is very nice example to start of with .. Could you please upgrade it to Spring Boot version 2.1.0.RELEASE?

### ISSUE THREAD

**Issue by JavaHelper** [kbastani/event-sourcing-microservices-basics#1]
This is very nice example to start of with .. Could you please upgrade it to Spring Boot version 2.1.0.RELEASE?

**Comment by kbastani** [comment]
The 2.1.0.RELEASE includes a defect that causes Eureka not to be able to register clients by instance IP address. Because of this issue, I have upgraded the project to a 2.0.6.RELEASE baseline. Once the issue is fixed, I will upgrade the project to 2.1.X.RELEASE using Atomist.

**Comment by kbastani** [comment]
The project has been upgraded to JDK 11 for [edge-service, aggregate-service, discovery-service]. JDK 8 is still being used for [user-service, friend-service]. The docker compose file has been upgraded to the version 3.x specification, which will now allow you to deploy docker compose files to kubernetes. The Spring Boot version for all projects has been upgraded to a 2.0.7 stable baseline. I will check the latest Spring Boot stable release (2.1.1) within the next week to determine if its transitive dependencies for Spring Cloud and Eureka do not break functionality for discovery clients.

Enjoy.
